-- ====================================================================
-- ORACLE DATACORE - TABLESPACE & SCHEMA CREATION SCRIPT
-- Target Database: Oracle Database 11g / 12c / 18c / 19c / 21c / 23c
-- Platform: Linux (RHEL/CentOS/Ubuntu/Oracle Linux) & Windows Server
-- ====================================================================

-- 1. CONNECT AS SYSDBA
-- sqlplus sys/password@localhost:1521/ORCL as sysdba

-- 2. CREATE DEDICATED TABLESPACE FOR DATACORE
CREATE TABLESPACE DATACORE_TS
  DATAFILE 'datacore_ts01.dbf' 
  SIZE 200M 
  AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
  LOGGING
  EXTENT MANAGEMENT LOCAL AUTOALLOCATE
  SEGMENT SPACE MANAGEMENT AUTO;

-- 3. CREATE DEDICATED ORACLE USER SCHEMA
CREATE USER datacore_admin IDENTIFIED BY "Password123"
  DEFAULT TABLESPACE DATACORE_TS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON DATACORE_TS;

-- 4. GRANT NECESSARY PRIVILEGES
GRANT CONNECT, RESOURCE, DBA TO datacore_admin;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE PROCEDURE, CREATE VIEW TO datacore_admin;

-- CONNECT AS THE NEW USER
-- CONNECT datacore_admin/Password123@localhost:1521/ORCL;

-- 5. CREATE CORE TABLES IN DATACORE_TS TABLESPACE

-- A. NODES TABLE
CREATE TABLE ORACLE_NODES (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL,
    IP VARCHAR2(64) NOT NULL,
    PORT NUMBER(5) DEFAULT 22,
    USERNAME VARCHAR2(64) NOT NULL,
    STATUS VARCHAR2(32) DEFAULT 'ONLINE',
    CPU_USAGE NUMBER(5,2) DEFAULT 0,
    MEMORY_USAGE NUMBER(5,2) DEFAULT 0,
    DISK_USAGE NUMBER(5,2) DEFAULT 0,
    LAST_PING TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE DATACORE_TS;

-- B. PRIMARY DATABASES TABLE
CREATE TABLE PRIMARY_DATABASES (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL,
    HOST VARCHAR2(128) NOT NULL,
    PORT NUMBER(5) DEFAULT 1521,
    SERVICE_NAME VARCHAR2(128) NOT NULL,
    ROLE VARCHAR2(32) DEFAULT 'PRIMARY',
    STATUS VARCHAR2(32) DEFAULT 'OPEN',
    MODE_TYPE VARCHAR2(32) DEFAULT 'READ WRITE',
    OPEN_MODE VARCHAR2(32) DEFAULT 'READ WRITE',
    LOG_MODE VARCHAR2(32) DEFAULT 'ARCHIVELOG',
    CURRENT_SCN NUMBER(20) DEFAULT 0,
    APPLIED_SCN NUMBER(20) DEFAULT 0,
    GAP_COUNT NUMBER(10) DEFAULT 0,
    DATA_GUARD_STATUS VARCHAR2(32) DEFAULT 'SYNCHRONIZED',
    TOTAL_REDO_MB NUMBER(12,2) DEFAULT 0,
    APPLIED_REDO_MB NUMBER(12,2) DEFAULT 0
) TABLESPACE DATACORE_TS;

-- C. STANDBY DATABASES TABLE
CREATE TABLE STANDBY_DATABASES (
    ID VARCHAR2(64) PRIMARY KEY,
    NAME VARCHAR2(128) NOT NULL,
    HOST VARCHAR2(128) NOT NULL,
    PORT NUMBER(5) DEFAULT 1521,
    SERVICE_NAME VARCHAR2(128) NOT NULL,
    PRIMARY_DB_ID VARCHAR2(64) NOT NULL,
    ROLE VARCHAR2(32) DEFAULT 'PHYSICAL STANDBY',
    STATUS VARCHAR2(32) DEFAULT 'MOUNTED',
    MODE_TYPE VARCHAR2(32) DEFAULT 'READ ONLY WITH APPLY',
    SYNC_STATUS VARCHAR2(32) DEFAULT 'SYNCHRONIZED',
    TRANSPORT_STATUS VARCHAR2(32) DEFAULT 'VALID',
    APPLY_RATE_MBS NUMBER(8,2) DEFAULT 0,
    LAG_SECONDS NUMBER(10) DEFAULT 0,
    MRP_RUNNING NUMBER(1) DEFAULT 1
) TABLESPACE DATACORE_TS;

-- D. USERS ACCOUNTS TABLE
CREATE TABLE USER_ACCOUNTS (
    ID VARCHAR2(64) PRIMARY KEY,
    USERNAME VARCHAR2(64) UNIQUE NOT NULL,
    EMAIL VARCHAR2(128) UNIQUE NOT NULL,
    PHONE VARCHAR2(32),
    ROLE VARCHAR2(32) DEFAULT 'MEMBER',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_LOGIN TIMESTAMP,
    AVATAR_URL CLOB
) TABLESPACE DATACORE_TS;

-- E. EMERGENCY DISPATCH LOGS
CREATE TABLE EMERGENCY_LOGS (
    ID VARCHAR2(64) PRIMARY KEY,
    LOG_TYPE VARCHAR2(16) NOT NULL,
    RECIPIENT_EMAIL VARCHAR2(128),
    RECIPIENT_PHONE VARCHAR2(32),
    EVENT_TYPE VARCHAR2(64),
    SUBJECT VARCHAR2(256),
    BODY CLOB,
    STATUS VARCHAR2(32) DEFAULT 'DISPATCHED',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE DATACORE_TS;

-- F. PORTAL BRANDING & CONFIG
CREATE TABLE PORTAL_BRANDING (
    ID NUMBER(1) PRIMARY KEY,
    PORTAL_NAME VARCHAR2(128) DEFAULT 'Oracle DataCore',
    PORTAL_SUBTITLE VARCHAR2(128) DEFAULT 'Enterprise Portal',
    LOGO_URL CLOB,
    AVATAR_URL CLOB,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) TABLESPACE DATACORE_TS;

-- INSERT DEFAULT BRANDING ROW
INSERT INTO PORTAL_BRANDING (ID, PORTAL_NAME, PORTAL_SUBTITLE) 
VALUES (1, 'Oracle DataCore', 'Enterprise Portal');

COMMIT;

-- VERIFY TABLESPACE SETUP
SELECT TABLESPACE_NAME, BYTES/1024/1024 AS SIZE_MB, MAXBYTES/1024/1024 AS MAX_SIZE_MB 
FROM DBA_DATA_FILES 
WHERE TABLESPACE_NAME = 'DATACORE_TS';
